DEVOPS-142 fix quotation issues (#34)

diff --git a/.github/workflows/release_candidate.yml b/.github/workflows/release_candidate.yml
--- a/.github/workflows/release_candidate.yml
+++ b/.github/workflows/release_candidate.yml
@@ -28,8 +28,8 @@ jobs:
 
       - name: Check branch name syntax
         run: |
-          if ! [[ "${GITHUB_BRANCH}" =~ '^release/v[0-9]+\.[0-9]+\.[0-9]+$' ]]; then
-            echo "::error title=BranchNameError::Invalid syntax for release branch name: ${GITHUB_BRANCH}. Please use `release/v` followed by a semantic version" 
+          if ! [[ "${GITHUB_BRANCH}" =~ ^release/v[0-9]+.[0-9]+.[0-9]+$ ]]; then
+            echo "::error title=BranchNameError::Invalid syntax for release branch name: ${GITHUB_BRANCH}. Please use 'release/v' followed by a semantic version" 
             exit 1
           fi
 
